language: node_js

os:
  - linux
  - osx

node_js:
  - 'lts/*'
  - '10'
  - '8'

script:
  - npm install
  - npm run test

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  keep_history: true
  fqdn: https://covidonation.com
  github_token: $GITHUB_TOKEN
  on:
    branch: master
