language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
