language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

script:
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: always

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: build
  project_name: covidonation
  name: Jabran Rafique
  email: hello@jabran.me
  github_token: $GITHUB_TOKEN
  on:
    branch: master

after_deploy:
  - git branch -a
  - git fetch --all
  - git remote -v
