/* Automatically generated file. DO NOT edit manually. See setup.js for details. */
import React from 'react';
import { Switch } from 'react-router-dom';

import CountryPage from '../pages/country';
import CovidRoute from './covid-route';

const CountryRoutes = () => (
  <Switch>
    <CovidRoute exact path="/afghanistan" slug="afghanistan" render={(props) => <CountryPage slug="afghanistan" {...props} />} />
<CovidRoute exact path="/ala-aland-islands" slug="ala-aland-islands" render={(props) => <CountryPage slug="ala-aland-islands" {...props} />} />
<CovidRoute exact path="/albania" slug="albania" render={(props) => <CountryPage slug="albania" {...props} />} />
<CovidRoute exact path="/algeria" slug="algeria" render={(props) => <CountryPage slug="algeria" {...props} />} />
<CovidRoute exact path="/american-samoa" slug="american-samoa" render={(props) => <CountryPage slug="american-samoa" {...props} />} />
<CovidRoute exact path="/andorra" slug="andorra" render={(props) => <CountryPage slug="andorra" {...props} />} />
<CovidRoute exact path="/angola" slug="angola" render={(props) => <CountryPage slug="angola" {...props} />} />
<CovidRoute exact path="/anguilla" slug="anguilla" render={(props) => <CountryPage slug="anguilla" {...props} />} />
<CovidRoute exact path="/antarctica" slug="antarctica" render={(props) => <CountryPage slug="antarctica" {...props} />} />
<CovidRoute exact path="/antigua-and-barbuda" slug="antigua-and-barbuda" render={(props) => <CountryPage slug="antigua-and-barbuda" {...props} />} />
<CovidRoute exact path="/argentina" slug="argentina" render={(props) => <CountryPage slug="argentina" {...props} />} />
<CovidRoute exact path="/armenia" slug="armenia" render={(props) => <CountryPage slug="armenia" {...props} />} />
<CovidRoute exact path="/aruba" slug="aruba" render={(props) => <CountryPage slug="aruba" {...props} />} />
<CovidRoute exact path="/australia" slug="australia" render={(props) => <CountryPage slug="australia" {...props} />} />
<CovidRoute exact path="/austria" slug="austria" render={(props) => <CountryPage slug="austria" {...props} />} />
<CovidRoute exact path="/azerbaijan" slug="azerbaijan" render={(props) => <CountryPage slug="azerbaijan" {...props} />} />
<CovidRoute exact path="/bahamas" slug="bahamas" render={(props) => <CountryPage slug="bahamas" {...props} />} />
<CovidRoute exact path="/bahrain" slug="bahrain" render={(props) => <CountryPage slug="bahrain" {...props} />} />
<CovidRoute exact path="/bangladesh" slug="bangladesh" render={(props) => <CountryPage slug="bangladesh" {...props} />} />
<CovidRoute exact path="/barbados" slug="barbados" render={(props) => <CountryPage slug="barbados" {...props} />} />
<CovidRoute exact path="/belarus" slug="belarus" render={(props) => <CountryPage slug="belarus" {...props} />} />
<CovidRoute exact path="/belgium" slug="belgium" render={(props) => <CountryPage slug="belgium" {...props} />} />
<CovidRoute exact path="/belize" slug="belize" render={(props) => <CountryPage slug="belize" {...props} />} />
<CovidRoute exact path="/benin" slug="benin" render={(props) => <CountryPage slug="benin" {...props} />} />
<CovidRoute exact path="/bermuda" slug="bermuda" render={(props) => <CountryPage slug="bermuda" {...props} />} />
<CovidRoute exact path="/bhutan" slug="bhutan" render={(props) => <CountryPage slug="bhutan" {...props} />} />
<CovidRoute exact path="/bolivia" slug="bolivia" render={(props) => <CountryPage slug="bolivia" {...props} />} />
<CovidRoute exact path="/bosnia-and-herzegovina" slug="bosnia-and-herzegovina" render={(props) => <CountryPage slug="bosnia-and-herzegovina" {...props} />} />
<CovidRoute exact path="/botswana" slug="botswana" render={(props) => <CountryPage slug="botswana" {...props} />} />
<CovidRoute exact path="/bouvet-island" slug="bouvet-island" render={(props) => <CountryPage slug="bouvet-island" {...props} />} />
<CovidRoute exact path="/brazil" slug="brazil" render={(props) => <CountryPage slug="brazil" {...props} />} />
<CovidRoute exact path="/british-indian-ocean-territory" slug="british-indian-ocean-territory" render={(props) => <CountryPage slug="british-indian-ocean-territory" {...props} />} />
<CovidRoute exact path="/british-virgin-islands" slug="british-virgin-islands" render={(props) => <CountryPage slug="british-virgin-islands" {...props} />} />
<CovidRoute exact path="/brunei" slug="brunei" render={(props) => <CountryPage slug="brunei" {...props} />} />
<CovidRoute exact path="/bulgaria" slug="bulgaria" render={(props) => <CountryPage slug="bulgaria" {...props} />} />
<CovidRoute exact path="/burkina-faso" slug="burkina-faso" render={(props) => <CountryPage slug="burkina-faso" {...props} />} />
<CovidRoute exact path="/burundi" slug="burundi" render={(props) => <CountryPage slug="burundi" {...props} />} />
<CovidRoute exact path="/cambodia" slug="cambodia" render={(props) => <CountryPage slug="cambodia" {...props} />} />
<CovidRoute exact path="/cameroon" slug="cameroon" render={(props) => <CountryPage slug="cameroon" {...props} />} />
<CovidRoute exact path="/canada" slug="canada" render={(props) => <CountryPage slug="canada" {...props} />} />
<CovidRoute exact path="/cape-verde" slug="cape-verde" render={(props) => <CountryPage slug="cape-verde" {...props} />} />
<CovidRoute exact path="/cayman-islands" slug="cayman-islands" render={(props) => <CountryPage slug="cayman-islands" {...props} />} />
<CovidRoute exact path="/central-african-republic" slug="central-african-republic" render={(props) => <CountryPage slug="central-african-republic" {...props} />} />
<CovidRoute exact path="/chad" slug="chad" render={(props) => <CountryPage slug="chad" {...props} />} />
<CovidRoute exact path="/chile" slug="chile" render={(props) => <CountryPage slug="chile" {...props} />} />
<CovidRoute exact path="/china" slug="china" render={(props) => <CountryPage slug="china" {...props} />} />
<CovidRoute exact path="/christmas-island" slug="christmas-island" render={(props) => <CountryPage slug="christmas-island" {...props} />} />
<CovidRoute exact path="/cocos-keeling-islands" slug="cocos-keeling-islands" render={(props) => <CountryPage slug="cocos-keeling-islands" {...props} />} />
<CovidRoute exact path="/colombia" slug="colombia" render={(props) => <CountryPage slug="colombia" {...props} />} />
<CovidRoute exact path="/comoros" slug="comoros" render={(props) => <CountryPage slug="comoros" {...props} />} />
<CovidRoute exact path="/congo-brazzaville" slug="congo-brazzaville" render={(props) => <CountryPage slug="congo-brazzaville" {...props} />} />
<CovidRoute exact path="/congo-kinshasa" slug="congo-kinshasa" render={(props) => <CountryPage slug="congo-kinshasa" {...props} />} />
<CovidRoute exact path="/cook-islands" slug="cook-islands" render={(props) => <CountryPage slug="cook-islands" {...props} />} />
<CovidRoute exact path="/costa-rica" slug="costa-rica" render={(props) => <CountryPage slug="costa-rica" {...props} />} />
<CovidRoute exact path="/cote-divoire" slug="cote-divoire" render={(props) => <CountryPage slug="cote-divoire" {...props} />} />
<CovidRoute exact path="/croatia" slug="croatia" render={(props) => <CountryPage slug="croatia" {...props} />} />
<CovidRoute exact path="/cuba" slug="cuba" render={(props) => <CountryPage slug="cuba" {...props} />} />
<CovidRoute exact path="/cyprus" slug="cyprus" render={(props) => <CountryPage slug="cyprus" {...props} />} />
<CovidRoute exact path="/czech-republic" slug="czech-republic" render={(props) => <CountryPage slug="czech-republic" {...props} />} />
<CovidRoute exact path="/denmark" slug="denmark" render={(props) => <CountryPage slug="denmark" {...props} />} />
<CovidRoute exact path="/djibouti" slug="djibouti" render={(props) => <CountryPage slug="djibouti" {...props} />} />
<CovidRoute exact path="/dominica" slug="dominica" render={(props) => <CountryPage slug="dominica" {...props} />} />
<CovidRoute exact path="/dominican-republic" slug="dominican-republic" render={(props) => <CountryPage slug="dominican-republic" {...props} />} />
<CovidRoute exact path="/ecuador" slug="ecuador" render={(props) => <CountryPage slug="ecuador" {...props} />} />
<CovidRoute exact path="/egypt" slug="egypt" render={(props) => <CountryPage slug="egypt" {...props} />} />
<CovidRoute exact path="/el-salvador" slug="el-salvador" render={(props) => <CountryPage slug="el-salvador" {...props} />} />
<CovidRoute exact path="/equatorial-guinea" slug="equatorial-guinea" render={(props) => <CountryPage slug="equatorial-guinea" {...props} />} />
<CovidRoute exact path="/eritrea" slug="eritrea" render={(props) => <CountryPage slug="eritrea" {...props} />} />
<CovidRoute exact path="/estonia" slug="estonia" render={(props) => <CountryPage slug="estonia" {...props} />} />
<CovidRoute exact path="/ethiopia" slug="ethiopia" render={(props) => <CountryPage slug="ethiopia" {...props} />} />
<CovidRoute exact path="/falkland-islands-malvinas" slug="falkland-islands-malvinas" render={(props) => <CountryPage slug="falkland-islands-malvinas" {...props} />} />
<CovidRoute exact path="/faroe-islands" slug="faroe-islands" render={(props) => <CountryPage slug="faroe-islands" {...props} />} />
<CovidRoute exact path="/fiji" slug="fiji" render={(props) => <CountryPage slug="fiji" {...props} />} />
<CovidRoute exact path="/finland" slug="finland" render={(props) => <CountryPage slug="finland" {...props} />} />
<CovidRoute exact path="/france" slug="france" render={(props) => <CountryPage slug="france" {...props} />} />
<CovidRoute exact path="/french-guiana" slug="french-guiana" render={(props) => <CountryPage slug="french-guiana" {...props} />} />
<CovidRoute exact path="/french-polynesia" slug="french-polynesia" render={(props) => <CountryPage slug="french-polynesia" {...props} />} />
<CovidRoute exact path="/french-southern-territories" slug="french-southern-territories" render={(props) => <CountryPage slug="french-southern-territories" {...props} />} />
<CovidRoute exact path="/gabon" slug="gabon" render={(props) => <CountryPage slug="gabon" {...props} />} />
<CovidRoute exact path="/gambia" slug="gambia" render={(props) => <CountryPage slug="gambia" {...props} />} />
<CovidRoute exact path="/georgia" slug="georgia" render={(props) => <CountryPage slug="georgia" {...props} />} />
<CovidRoute exact path="/germany" slug="germany" render={(props) => <CountryPage slug="germany" {...props} />} />
<CovidRoute exact path="/ghana" slug="ghana" render={(props) => <CountryPage slug="ghana" {...props} />} />
<CovidRoute exact path="/gibraltar" slug="gibraltar" render={(props) => <CountryPage slug="gibraltar" {...props} />} />
<CovidRoute exact path="/greece" slug="greece" render={(props) => <CountryPage slug="greece" {...props} />} />
<CovidRoute exact path="/greenland" slug="greenland" render={(props) => <CountryPage slug="greenland" {...props} />} />
<CovidRoute exact path="/grenada" slug="grenada" render={(props) => <CountryPage slug="grenada" {...props} />} />
<CovidRoute exact path="/guadeloupe" slug="guadeloupe" render={(props) => <CountryPage slug="guadeloupe" {...props} />} />
<CovidRoute exact path="/guam" slug="guam" render={(props) => <CountryPage slug="guam" {...props} />} />
<CovidRoute exact path="/guatemala" slug="guatemala" render={(props) => <CountryPage slug="guatemala" {...props} />} />
<CovidRoute exact path="/guernsey" slug="guernsey" render={(props) => <CountryPage slug="guernsey" {...props} />} />
<CovidRoute exact path="/guinea-bissau" slug="guinea-bissau" render={(props) => <CountryPage slug="guinea-bissau" {...props} />} />
<CovidRoute exact path="/guinea" slug="guinea" render={(props) => <CountryPage slug="guinea" {...props} />} />
<CovidRoute exact path="/guyana" slug="guyana" render={(props) => <CountryPage slug="guyana" {...props} />} />
<CovidRoute exact path="/haiti" slug="haiti" render={(props) => <CountryPage slug="haiti" {...props} />} />
<CovidRoute exact path="/heard-and-mcdonald-islands" slug="heard-and-mcdonald-islands" render={(props) => <CountryPage slug="heard-and-mcdonald-islands" {...props} />} />
<CovidRoute exact path="/holy-see-vatican-city-state" slug="holy-see-vatican-city-state" render={(props) => <CountryPage slug="holy-see-vatican-city-state" {...props} />} />
<CovidRoute exact path="/honduras" slug="honduras" render={(props) => <CountryPage slug="honduras" {...props} />} />
<CovidRoute exact path="/hong-kong-sar-china" slug="hong-kong-sar-china" render={(props) => <CountryPage slug="hong-kong-sar-china" {...props} />} />
<CovidRoute exact path="/hungary" slug="hungary" render={(props) => <CountryPage slug="hungary" {...props} />} />
<CovidRoute exact path="/iceland" slug="iceland" render={(props) => <CountryPage slug="iceland" {...props} />} />
<CovidRoute exact path="/india" slug="india" render={(props) => <CountryPage slug="india" {...props} />} />
<CovidRoute exact path="/indonesia" slug="indonesia" render={(props) => <CountryPage slug="indonesia" {...props} />} />
<CovidRoute exact path="/iran" slug="iran" render={(props) => <CountryPage slug="iran" {...props} />} />
<CovidRoute exact path="/iraq" slug="iraq" render={(props) => <CountryPage slug="iraq" {...props} />} />
<CovidRoute exact path="/ireland" slug="ireland" render={(props) => <CountryPage slug="ireland" {...props} />} />
<CovidRoute exact path="/isle-of-man" slug="isle-of-man" render={(props) => <CountryPage slug="isle-of-man" {...props} />} />
<CovidRoute exact path="/israel" slug="israel" render={(props) => <CountryPage slug="israel" {...props} />} />
<CovidRoute exact path="/italy" slug="italy" render={(props) => <CountryPage slug="italy" {...props} />} />
<CovidRoute exact path="/jamaica" slug="jamaica" render={(props) => <CountryPage slug="jamaica" {...props} />} />
<CovidRoute exact path="/japan" slug="japan" render={(props) => <CountryPage slug="japan" {...props} />} />
<CovidRoute exact path="/jersey" slug="jersey" render={(props) => <CountryPage slug="jersey" {...props} />} />
<CovidRoute exact path="/jordan" slug="jordan" render={(props) => <CountryPage slug="jordan" {...props} />} />
<CovidRoute exact path="/kazakhstan" slug="kazakhstan" render={(props) => <CountryPage slug="kazakhstan" {...props} />} />
<CovidRoute exact path="/kenya" slug="kenya" render={(props) => <CountryPage slug="kenya" {...props} />} />
<CovidRoute exact path="/kiribati" slug="kiribati" render={(props) => <CountryPage slug="kiribati" {...props} />} />
<CovidRoute exact path="/korea-north" slug="korea-north" render={(props) => <CountryPage slug="korea-north" {...props} />} />
<CovidRoute exact path="/korea-south" slug="korea-south" render={(props) => <CountryPage slug="korea-south" {...props} />} />
<CovidRoute exact path="/kosovo" slug="kosovo" render={(props) => <CountryPage slug="kosovo" {...props} />} />
<CovidRoute exact path="/kuwait" slug="kuwait" render={(props) => <CountryPage slug="kuwait" {...props} />} />
<CovidRoute exact path="/kyrgyzstan" slug="kyrgyzstan" render={(props) => <CountryPage slug="kyrgyzstan" {...props} />} />
<CovidRoute exact path="/lao-pdr" slug="lao-pdr" render={(props) => <CountryPage slug="lao-pdr" {...props} />} />
<CovidRoute exact path="/latvia" slug="latvia" render={(props) => <CountryPage slug="latvia" {...props} />} />
<CovidRoute exact path="/lebanon" slug="lebanon" render={(props) => <CountryPage slug="lebanon" {...props} />} />
<CovidRoute exact path="/lesotho" slug="lesotho" render={(props) => <CountryPage slug="lesotho" {...props} />} />
<CovidRoute exact path="/liberia" slug="liberia" render={(props) => <CountryPage slug="liberia" {...props} />} />
<CovidRoute exact path="/libya" slug="libya" render={(props) => <CountryPage slug="libya" {...props} />} />
<CovidRoute exact path="/liechtenstein" slug="liechtenstein" render={(props) => <CountryPage slug="liechtenstein" {...props} />} />
<CovidRoute exact path="/lithuania" slug="lithuania" render={(props) => <CountryPage slug="lithuania" {...props} />} />
<CovidRoute exact path="/luxembourg" slug="luxembourg" render={(props) => <CountryPage slug="luxembourg" {...props} />} />
<CovidRoute exact path="/macao-sar-china" slug="macao-sar-china" render={(props) => <CountryPage slug="macao-sar-china" {...props} />} />
<CovidRoute exact path="/macedonia" slug="macedonia" render={(props) => <CountryPage slug="macedonia" {...props} />} />
<CovidRoute exact path="/madagascar" slug="madagascar" render={(props) => <CountryPage slug="madagascar" {...props} />} />
<CovidRoute exact path="/malawi" slug="malawi" render={(props) => <CountryPage slug="malawi" {...props} />} />
<CovidRoute exact path="/malaysia" slug="malaysia" render={(props) => <CountryPage slug="malaysia" {...props} />} />
<CovidRoute exact path="/maldives" slug="maldives" render={(props) => <CountryPage slug="maldives" {...props} />} />
<CovidRoute exact path="/mali" slug="mali" render={(props) => <CountryPage slug="mali" {...props} />} />
<CovidRoute exact path="/malta" slug="malta" render={(props) => <CountryPage slug="malta" {...props} />} />
<CovidRoute exact path="/marshall-islands" slug="marshall-islands" render={(props) => <CountryPage slug="marshall-islands" {...props} />} />
<CovidRoute exact path="/martinique" slug="martinique" render={(props) => <CountryPage slug="martinique" {...props} />} />
<CovidRoute exact path="/mauritania" slug="mauritania" render={(props) => <CountryPage slug="mauritania" {...props} />} />
<CovidRoute exact path="/mauritius" slug="mauritius" render={(props) => <CountryPage slug="mauritius" {...props} />} />
<CovidRoute exact path="/mayotte" slug="mayotte" render={(props) => <CountryPage slug="mayotte" {...props} />} />
<CovidRoute exact path="/mexico" slug="mexico" render={(props) => <CountryPage slug="mexico" {...props} />} />
<CovidRoute exact path="/micronesia" slug="micronesia" render={(props) => <CountryPage slug="micronesia" {...props} />} />
<CovidRoute exact path="/moldova" slug="moldova" render={(props) => <CountryPage slug="moldova" {...props} />} />
<CovidRoute exact path="/monaco" slug="monaco" render={(props) => <CountryPage slug="monaco" {...props} />} />
<CovidRoute exact path="/mongolia" slug="mongolia" render={(props) => <CountryPage slug="mongolia" {...props} />} />
<CovidRoute exact path="/montenegro" slug="montenegro" render={(props) => <CountryPage slug="montenegro" {...props} />} />
<CovidRoute exact path="/montserrat" slug="montserrat" render={(props) => <CountryPage slug="montserrat" {...props} />} />
<CovidRoute exact path="/morocco" slug="morocco" render={(props) => <CountryPage slug="morocco" {...props} />} />
<CovidRoute exact path="/mozambique" slug="mozambique" render={(props) => <CountryPage slug="mozambique" {...props} />} />
<CovidRoute exact path="/myanmar" slug="myanmar" render={(props) => <CountryPage slug="myanmar" {...props} />} />
<CovidRoute exact path="/namibia" slug="namibia" render={(props) => <CountryPage slug="namibia" {...props} />} />
<CovidRoute exact path="/nauru" slug="nauru" render={(props) => <CountryPage slug="nauru" {...props} />} />
<CovidRoute exact path="/nepal" slug="nepal" render={(props) => <CountryPage slug="nepal" {...props} />} />
<CovidRoute exact path="/netherlands-antilles" slug="netherlands-antilles" render={(props) => <CountryPage slug="netherlands-antilles" {...props} />} />
<CovidRoute exact path="/netherlands" slug="netherlands" render={(props) => <CountryPage slug="netherlands" {...props} />} />
<CovidRoute exact path="/new-caledonia" slug="new-caledonia" render={(props) => <CountryPage slug="new-caledonia" {...props} />} />
<CovidRoute exact path="/new-zealand" slug="new-zealand" render={(props) => <CountryPage slug="new-zealand" {...props} />} />
<CovidRoute exact path="/nicaragua" slug="nicaragua" render={(props) => <CountryPage slug="nicaragua" {...props} />} />
<CovidRoute exact path="/niger" slug="niger" render={(props) => <CountryPage slug="niger" {...props} />} />
<CovidRoute exact path="/nigeria" slug="nigeria" render={(props) => <CountryPage slug="nigeria" {...props} />} />
<CovidRoute exact path="/niue" slug="niue" render={(props) => <CountryPage slug="niue" {...props} />} />
<CovidRoute exact path="/norfolk-island" slug="norfolk-island" render={(props) => <CountryPage slug="norfolk-island" {...props} />} />
<CovidRoute exact path="/northern-mariana-islands" slug="northern-mariana-islands" render={(props) => <CountryPage slug="northern-mariana-islands" {...props} />} />
<CovidRoute exact path="/norway" slug="norway" render={(props) => <CountryPage slug="norway" {...props} />} />
<CovidRoute exact path="/oman" slug="oman" render={(props) => <CountryPage slug="oman" {...props} />} />
<CovidRoute exact path="/pakistan" slug="pakistan" render={(props) => <CountryPage slug="pakistan" {...props} />} />
<CovidRoute exact path="/palau" slug="palau" render={(props) => <CountryPage slug="palau" {...props} />} />
<CovidRoute exact path="/palestine" slug="palestine" render={(props) => <CountryPage slug="palestine" {...props} />} />
<CovidRoute exact path="/panama" slug="panama" render={(props) => <CountryPage slug="panama" {...props} />} />
<CovidRoute exact path="/papua-new-guinea" slug="papua-new-guinea" render={(props) => <CountryPage slug="papua-new-guinea" {...props} />} />
<CovidRoute exact path="/paraguay" slug="paraguay" render={(props) => <CountryPage slug="paraguay" {...props} />} />
<CovidRoute exact path="/peru" slug="peru" render={(props) => <CountryPage slug="peru" {...props} />} />
<CovidRoute exact path="/philippines" slug="philippines" render={(props) => <CountryPage slug="philippines" {...props} />} />
<CovidRoute exact path="/pitcairn" slug="pitcairn" render={(props) => <CountryPage slug="pitcairn" {...props} />} />
<CovidRoute exact path="/poland" slug="poland" render={(props) => <CountryPage slug="poland" {...props} />} />
<CovidRoute exact path="/portugal" slug="portugal" render={(props) => <CountryPage slug="portugal" {...props} />} />
<CovidRoute exact path="/puerto-rico" slug="puerto-rico" render={(props) => <CountryPage slug="puerto-rico" {...props} />} />
<CovidRoute exact path="/qatar" slug="qatar" render={(props) => <CountryPage slug="qatar" {...props} />} />
<CovidRoute exact path="/reunion" slug="reunion" render={(props) => <CountryPage slug="reunion" {...props} />} />
<CovidRoute exact path="/romania" slug="romania" render={(props) => <CountryPage slug="romania" {...props} />} />
<CovidRoute exact path="/russia" slug="russia" render={(props) => <CountryPage slug="russia" {...props} />} />
<CovidRoute exact path="/rwanda" slug="rwanda" render={(props) => <CountryPage slug="rwanda" {...props} />} />
<CovidRoute exact path="/saint-barthelemy" slug="saint-barthelemy" render={(props) => <CountryPage slug="saint-barthelemy" {...props} />} />
<CovidRoute exact path="/saint-helena" slug="saint-helena" render={(props) => <CountryPage slug="saint-helena" {...props} />} />
<CovidRoute exact path="/saint-kitts-and-nevis" slug="saint-kitts-and-nevis" render={(props) => <CountryPage slug="saint-kitts-and-nevis" {...props} />} />
<CovidRoute exact path="/saint-lucia" slug="saint-lucia" render={(props) => <CountryPage slug="saint-lucia" {...props} />} />
<CovidRoute exact path="/saint-martin-french-part" slug="saint-martin-french-part" render={(props) => <CountryPage slug="saint-martin-french-part" {...props} />} />
<CovidRoute exact path="/saint-pierre-and-miquelon" slug="saint-pierre-and-miquelon" render={(props) => <CountryPage slug="saint-pierre-and-miquelon" {...props} />} />
<CovidRoute exact path="/saint-vincent-and-the-grenadines" slug="saint-vincent-and-the-grenadines" render={(props) => <CountryPage slug="saint-vincent-and-the-grenadines" {...props} />} />
<CovidRoute exact path="/samoa" slug="samoa" render={(props) => <CountryPage slug="samoa" {...props} />} />
<CovidRoute exact path="/san-marino" slug="san-marino" render={(props) => <CountryPage slug="san-marino" {...props} />} />
<CovidRoute exact path="/sao-tome-and-principe" slug="sao-tome-and-principe" render={(props) => <CountryPage slug="sao-tome-and-principe" {...props} />} />
<CovidRoute exact path="/saudi-arabia" slug="saudi-arabia" render={(props) => <CountryPage slug="saudi-arabia" {...props} />} />
<CovidRoute exact path="/senegal" slug="senegal" render={(props) => <CountryPage slug="senegal" {...props} />} />
<CovidRoute exact path="/serbia" slug="serbia" render={(props) => <CountryPage slug="serbia" {...props} />} />
<CovidRoute exact path="/seychelles" slug="seychelles" render={(props) => <CountryPage slug="seychelles" {...props} />} />
<CovidRoute exact path="/sierra-leone" slug="sierra-leone" render={(props) => <CountryPage slug="sierra-leone" {...props} />} />
<CovidRoute exact path="/singapore" slug="singapore" render={(props) => <CountryPage slug="singapore" {...props} />} />
<CovidRoute exact path="/slovakia" slug="slovakia" render={(props) => <CountryPage slug="slovakia" {...props} />} />
<CovidRoute exact path="/slovenia" slug="slovenia" render={(props) => <CountryPage slug="slovenia" {...props} />} />
<CovidRoute exact path="/solomon-islands" slug="solomon-islands" render={(props) => <CountryPage slug="solomon-islands" {...props} />} />
<CovidRoute exact path="/somalia" slug="somalia" render={(props) => <CountryPage slug="somalia" {...props} />} />
<CovidRoute exact path="/south-africa" slug="south-africa" render={(props) => <CountryPage slug="south-africa" {...props} />} />
<CovidRoute exact path="/south-georgia-and-the-south-sandwich-islands" slug="south-georgia-and-the-south-sandwich-islands" render={(props) => <CountryPage slug="south-georgia-and-the-south-sandwich-islands" {...props} />} />
<CovidRoute exact path="/south-sudan" slug="south-sudan" render={(props) => <CountryPage slug="south-sudan" {...props} />} />
<CovidRoute exact path="/spain" slug="spain" render={(props) => <CountryPage slug="spain" {...props} />} />
<CovidRoute exact path="/sri-lanka" slug="sri-lanka" render={(props) => <CountryPage slug="sri-lanka" {...props} />} />
<CovidRoute exact path="/sudan" slug="sudan" render={(props) => <CountryPage slug="sudan" {...props} />} />
<CovidRoute exact path="/suriname" slug="suriname" render={(props) => <CountryPage slug="suriname" {...props} />} />
<CovidRoute exact path="/svalbard-and-jan-mayen-islands" slug="svalbard-and-jan-mayen-islands" render={(props) => <CountryPage slug="svalbard-and-jan-mayen-islands" {...props} />} />
<CovidRoute exact path="/swaziland" slug="swaziland" render={(props) => <CountryPage slug="swaziland" {...props} />} />
<CovidRoute exact path="/sweden" slug="sweden" render={(props) => <CountryPage slug="sweden" {...props} />} />
<CovidRoute exact path="/switzerland" slug="switzerland" render={(props) => <CountryPage slug="switzerland" {...props} />} />
<CovidRoute exact path="/syria" slug="syria" render={(props) => <CountryPage slug="syria" {...props} />} />
<CovidRoute exact path="/taiwan" slug="taiwan" render={(props) => <CountryPage slug="taiwan" {...props} />} />
<CovidRoute exact path="/tajikistan" slug="tajikistan" render={(props) => <CountryPage slug="tajikistan" {...props} />} />
<CovidRoute exact path="/tanzania" slug="tanzania" render={(props) => <CountryPage slug="tanzania" {...props} />} />
<CovidRoute exact path="/thailand" slug="thailand" render={(props) => <CountryPage slug="thailand" {...props} />} />
<CovidRoute exact path="/timor-leste" slug="timor-leste" render={(props) => <CountryPage slug="timor-leste" {...props} />} />
<CovidRoute exact path="/togo" slug="togo" render={(props) => <CountryPage slug="togo" {...props} />} />
<CovidRoute exact path="/tokelau" slug="tokelau" render={(props) => <CountryPage slug="tokelau" {...props} />} />
<CovidRoute exact path="/tonga" slug="tonga" render={(props) => <CountryPage slug="tonga" {...props} />} />
<CovidRoute exact path="/trinidad-and-tobago" slug="trinidad-and-tobago" render={(props) => <CountryPage slug="trinidad-and-tobago" {...props} />} />
<CovidRoute exact path="/tunisia" slug="tunisia" render={(props) => <CountryPage slug="tunisia" {...props} />} />
<CovidRoute exact path="/turkey" slug="turkey" render={(props) => <CountryPage slug="turkey" {...props} />} />
<CovidRoute exact path="/turkmenistan" slug="turkmenistan" render={(props) => <CountryPage slug="turkmenistan" {...props} />} />
<CovidRoute exact path="/turks-and-caicos-islands" slug="turks-and-caicos-islands" render={(props) => <CountryPage slug="turks-and-caicos-islands" {...props} />} />
<CovidRoute exact path="/tuvalu" slug="tuvalu" render={(props) => <CountryPage slug="tuvalu" {...props} />} />
<CovidRoute exact path="/uganda" slug="uganda" render={(props) => <CountryPage slug="uganda" {...props} />} />
<CovidRoute exact path="/ukraine" slug="ukraine" render={(props) => <CountryPage slug="ukraine" {...props} />} />
<CovidRoute exact path="/united-arab-emirates" slug="united-arab-emirates" render={(props) => <CountryPage slug="united-arab-emirates" {...props} />} />
<CovidRoute exact path="/united-kingdom" slug="united-kingdom" render={(props) => <CountryPage slug="united-kingdom" {...props} />} />
<CovidRoute exact path="/united-states" slug="united-states" render={(props) => <CountryPage slug="united-states" {...props} />} />
<CovidRoute exact path="/uruguay" slug="uruguay" render={(props) => <CountryPage slug="uruguay" {...props} />} />
<CovidRoute exact path="/us-minor-outlying-islands" slug="us-minor-outlying-islands" render={(props) => <CountryPage slug="us-minor-outlying-islands" {...props} />} />
<CovidRoute exact path="/uzbekistan" slug="uzbekistan" render={(props) => <CountryPage slug="uzbekistan" {...props} />} />
<CovidRoute exact path="/vanuatu" slug="vanuatu" render={(props) => <CountryPage slug="vanuatu" {...props} />} />
<CovidRoute exact path="/venezuela" slug="venezuela" render={(props) => <CountryPage slug="venezuela" {...props} />} />
<CovidRoute exact path="/vietnam" slug="vietnam" render={(props) => <CountryPage slug="vietnam" {...props} />} />
<CovidRoute exact path="/virgin-islands" slug="virgin-islands" render={(props) => <CountryPage slug="virgin-islands" {...props} />} />
<CovidRoute exact path="/wallis-and-futuna-islands" slug="wallis-and-futuna-islands" render={(props) => <CountryPage slug="wallis-and-futuna-islands" {...props} />} />
<CovidRoute exact path="/western-sahara" slug="western-sahara" render={(props) => <CountryPage slug="western-sahara" {...props} />} />
<CovidRoute exact path="/yemen" slug="yemen" render={(props) => <CountryPage slug="yemen" {...props} />} />
<CovidRoute exact path="/zambia" slug="zambia" render={(props) => <CountryPage slug="zambia" {...props} />} />
<CovidRoute exact path="/zimbabwe" slug="zimbabwe" render={(props) => <CountryPage slug="zimbabwe" {...props} />} />
  </Switch>
);

export default CountryRoutes;