name: Automatic rebase
on:
  push:
    branches:
      - 'master'
jobs:
  rebase-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cirrus-actions/rebase@1.2
        with:
          type: now
          target_branch: 'develop'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
